[[aot]]
= Ahead of Time Optimizations

This chapter covers Spring's Ahead of Time (AOT) optimizations.

[[aot-introduction]]
== Introduction to Ahead of Time Optimizations

Spring's support for AOT optimizations is meant to inspect an `ApplicationContext` at build time and apply decisions and discovery logic that usually happens at runtime.
Doing so allows building an application startup arrangement that is more straightforward and focused on a fixed set of features based mainly on the classpath and the `Environment`.

Applying such optimizations early implies the following restrictions:

* The classpath is fixed and fully defined at build time.
* The beans defined in your application cannot change at runtime, meaning:
** `@Profile`, in particular profile-specific configuration need to be chosen at build time and can't be changed at runtime.
** Environment properties that impact the presence of a bean (`@Conditional`) are not supported.

When these restrictions are in place, it becomes possible to perform ahead-of-time processing during build-time and generate additional assets.
A Spring AOT processed application typically generates:

* Java source code
* Bytecode (typically for dynamic proxies)
* `RuntimeHints` for the use of reflection, resource loading, serialization, and JDK proxy.

NOTE: At the moment, AOT is focused on allowing Spring Applications to be deployed as native images using GraalVM.
We intend to offer more JVM-based use cases in future generations.

[[aot-basics]]
== AOT engine overview

The entry point of the AOT engine for processing an `ApplicationContext` arrangement is `ApplicationContextAotGenerator`. Based on a non-refreshed `GenericApplicationContext` and a `GenerationContext`, it takes care of the following steps:

* Refresh an `ApplicationContext` for AOT processing. Contrary to a traditional refresh, this version only creates bean definitions, not bean instances.
* Apply the available `BeanFactoryInitializationAotProcessor` that returns a code contribution for bean definitions that require it.
* For each bean definition, determine if it needs to be filtered, and apply the relevant `BeanRegistrationAotProcessor` accordingly. This part is taking care of providing a code contribution that registers the bean definition in an optimized fashion.

Once this process completes, the `GenerationContext` has been updated with the generated code, resources, and classes that are necessary for the application to run.
A `RuntimeHints` instance can also be used to generate the relevant GraalVM configuration files.

`ApplicationContextAotGenerator#processAheadOfTime` returns the class name of the `ApplicationContextInitializer` entry point that permits to start the context with AOT optimizations.

Those steps are covered in more details in the sections below.

[[aot-refresh]]
== Refresh for AOT Processing
Refresh for AOT processing is supported on any `GenericApplicationContext` implementations.
An application context is created with any number of entry points, usually in the form of `@Configuration`-annotated classes.

Let's take a basic example:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
@Configuration(proxyBeanMethods=false)
@ComponentScan
@Import({DataSourceConfiguration.class, ContainerConfiguration.class})
public class MyApplication {

}
----

Refresh for AOT processing is only applying a subset of what is happening with a <<beans-introduction,regular `refresh`>>.
It can be triggered as follows:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
GenericApplicationContext applicationContext = new AnnotatedConfigApplicationContext();
context.register(MyApplication.class);
context.refreshForAotProcessing();
----

In this mode, <<beans-factory-extension-factory-postprocessors,`BeanFactoryPostProcessor` implementations>> are invoked as usual.
This includes configuration class parsing, import selectors, classpath scanning, etc.
Such step makes sure that the `BeanRegistry` contains the relevant bean definitions for the application.
If bean definitions are guarded by conditions (such as `@Profile`), these are discarded at this stage.

Because this mode does not actually create bean instances, `BeanPostProcessor` are not invoked, except for specific variants that are relevant for AOT processing.
These are:
* `MergedBeanDefinitionPostProcessor` implementations post-process the bean definitions to extract additional settings, such as init and destroy methods.
* `SmartInstantiationAwareBeanPostProcessor` implementations help the AOT engine to determine if it has to manage a proxy for a particular bean.

The `BeanFactory` is therefore prepared and contains the bean definitions that are necessary for the application to run. It does not trigger bean instantiations but allow the AOT engine to inspect the beans that would be created at runtime.

[[aot-bean-factory-initialization-contributions]]
== Bean Factory Initialization AOT Contributions
Once the context has been refreshed for AOT processing, its bean factory can be processed.
Components that are willing to participate in this step can implement the {api-spring-framework}/beans/factory/aot/BeanFactoryInitializationAotProcessor.html[`BeanFactoryInitializationAotProcessor`] interface.
Each implementation can return an AOT contribution, based on the state of the bean factory.

An AOT contribution is a component that contributes generated code that reproduce a particular behavior.
It can also contribute `RuntimeHints` to indicate the need of reflection, resource loading, serialization, or JDK proxy.

`BeanFactoryInitializationAotProcessor` implementation should be registered in `META-INF/aot/spring.factories` with a key matching the fully qualified name of the interface.

It can also be implemented on a bean directly.
In this mode, the bean provides an AOT contribution equivalent of the feature is provides with a regular runtime.
As such, such a bean is automatically excluded from the AOT-optmized context.

[NOTE]
====
Using this interface on bean will cause the bean and **all** of its dependencies to be initialized during AOT processing.
We generally recommend that this interface is only used with infrastructure beans such as `BeanFactoryPostProcessor` which have limited dependencies and are already initialized early in the bean factory lifecycle.
If such a bean is registered using a factory `@Bean` method, make sure to make it `static` so that its enclosing `@Configuration` class does not have to be initialized.
====


[[aot-bean-registration-contributions]]
== Bean Registration AOT Contributions
A core `BeanFactoryInitializationAotProcessor` implementation is about collecting the necessary contributions for each candidate `BeanDefinition`.
It does so using a dedicated `BeanRegistrationAotProcessor`.

This interface is used as follows:

* On a `BeanPostProcessor` bean, to replace its runtime behavior.
For instance <<beans-factory-extension-bpp-examples-aabpp,`AutowiredAnnotationBeanPostProcessor`>> is implementing this interface to generate code that injects members annotated with `@Autowired`.
* On a type registered in `META-INF/aot/spring.factories` with a key matching the fully qualified name of the interface.
Typically used whe the bean definition needs to be tuned for specific features of the core framework.

[NOTE]
====
Using this interface on bean will cause the bean and **all** of its dependencies to be initialized during AOT processing.
We generally recommend that this interface is only used with infrastructure beans such as `BeanPostProcessor` which have limited dependencies and are already initialized early in the bean factory lifecycle.
If such a bean is registered using a factory `@Bean` method, make sure to make it `static` so that its enclosing `@Configuration` class does not have to be initialized.
====


